repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest version available in https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
    -   id: check-merge-conflict
        name: Check for merge conflict text
    -   id: trailing-whitespace
        name: Remove trailing whitespace

# Black - auto-formatting
  - repo: https://github.com/psf/black-pre-commit-mirror
    # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
    rev: 25.1.0
    hooks:
      - id: black
        name: Run Black formatting
        args: ["--config=pyproject.toml"]
        language_version: python3.10

# Pylint - Python code linting
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.7
    hooks:
    - id: pylint
      name: Run pylint
      entry: poetry run pylint
      args:
        [
          "app",
          "--rcfile=.pylintrc",
          "--fail-under=9.0",
          "--fail-on=E",
          "--output-format=colorized",
          "--reports=false"
        ]
      language: system
      pass_filenames: true # Pass changed filenames to pylint
      types: [python] # only run when python files where edited

# isort - sorting package imports
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.2
  #   hooks:
  #     - id: isort
  #       name: Run isort

# Shellcheck
  -   repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
      -   id: shellcheck
          name: Apply shellcheck
          types: [shell]  # Ensures it runs only on shell scripts
          # args: ["--severity=warning"]  # Optionally only show errors and warnings

# Python Unit Tests
  - repo: local
    hooks:
    - id: pytest
      name: Run Pytest Unit Tests
      entry: poetry run pytest
      args: ["tests/"] # tell pytest to use the `tests/` directory
      language: system
      types: [python] # only run when python files where edited
      pass_filenames: false # Don't pass changed filenames to pytest
